PKT_TIME_COLS = [
    'Time_cost',
    'Time_difference_between_packets_per_session',
    'Interval_of_arrival_time_of_forward_traffic',
    'Interval_of_arrival_time_of_backward_traffic',
    'inter_arrival_time_of_forward_traffic_enc',
    'inter_arrival_time_of_backward_traffic_enc',
    'ratio_to_previous_packet_enc',
]

SESS_TIME_COLS = [
    'flow duration',
    'flow_duration_of_forward_traffic',
    'flow_duration_of_backward_traffic',
    'mean_Time_difference_between_packets_per_session',
    'median_Time_difference_between_packets_per_session',
    'max_Time_difference_between_packets_per_session',
    'min_Time_difference_between_packets_per_session',
    'std_Time_difference_between_packets_per_session',
    'var_Time_difference_between_packets_per_session',
    'mean_Interval_of_arrival_time_of_forward_traffic',
    'median_Interval_of_arrival_time_of_forward_traffic',
    'max_Interval_of_arrival_time_of_forward_traffic',
    'min_Interval_of_arrival_time_of_forward_traffic',
    'std_Interval_of_arrival_time_of_forward_traffic',
    'var_Interval_of_arrival_time_of_forward_traffic',
    'mean_Interval_of_arrival_time_of_backward_traffic',
    'median_Interval_of_arrival_time_of_backward_traffic',
    'max_Interval_of_arrival_time_of_backward_traffic',
    'min_Interval_of_arrival_time_of_backward_traffic',
    'std_Interval_of_arrival_time_of_backward_traffic',
    'var_Interval_of_arrival_time_of_backward_traffic',
    'total_ttl_forward_traffic',
    'std_ttl_forward_traffic',
    'mean_ttl_forward_traffic',
    'max_ttl_forward_traffic',
    'min_ttl_forward_traffic',
    'var_ttl_forward_traffic',
    'median_ttl_forward_traffic',
    'total_ttl_backward_traffic',
    'std_ttl_backward_traffic',
    'mean_ttl_backward_traffic',
    'max_ttl_backward_traffic',
    'min_ttl_backward_traffic',
    'var_ttl_backward_traffic',
    'median_ttl_backward_traffic',
    'flow_duration_enc',
    'flow_duration_of_forward_traffic_enc',
    'flow_duration_of_backward_traffic_enc',
    'mean_Interval_of_arrival_time_of_forward_traffic_enc',
    'median_Interval_of_arrival_time_of_forward_traffic_enc',
    'max_Interval_of_arrival_time_of_forward_traffic_enc',
    'min_Interval_of_arrival_time_of_forward_traffic_enc',
    'std_Interval_of_arrival_time_of_forward_traffic_enc',
    'var_Interval_of_arrival_time_of_forward_traffic_enc',
    'mean_Interval_of_arrival_time_of_backward_traffic_enc',
    'median_Interval_of_arrival_time_of_backward_traffic_enc',
    'max_Interval_of_arrival_time_of_backward_traffic_enc',
    'min_Interval_of_arrival_time_of_backward_traffic_enc',
    'std_Interval_of_arrival_time_of_backward_traffic_enc',
    'var_Interval_of_arrival_time_of_backward_traffic_enc',
    'total_ttl_forward_traffic_enc',
    'std_ttl_forward_traffic_enc',
    'mean_ttl_forward_traffic_enc',
    'max_ttl_forward_traffic_enc',
    'min_ttl_forward_traffic_enc',
    'var_ttl_forward_traffic_enc',
    'median_ttl_forward_traffic_enc',
    'total_ttl_backward_traffic_enc',
    'std_ttl_backward_traffic_enc',
    'mean_ttl_backward_traffic_enc',
    'max_ttl_backward_traffic_enc',
    'min_ttl_backward_traffic_enc',
    'var_ttl_backward_traffic_enc',
    'median_ttl_backward_traffic_enc',
    'flow_duration_ratio',
    'flow_duration_of_forward_traffic_ratio',
    'flow_duration_of_backward_traffic_ratio',
    'mean_Interval_of_arrival_time_of_forward_traffic_ratio',
    'median_Interval_of_arrival_time_of_forward_traffic_ratio',
    'max_Interval_of_arrival_time_of_forward_traffic_ratio',
    'min_Interval_of_arrival_time_of_forward_traffic_ratio',
    'std_Interval_of_arrival_time_of_forward_traffic_ratio',
    'var_Interval_of_arrival_time_of_forward_traffic_ratio',
    'mean_Interval_of_arrival_time_of_backward_traffic_ratio',
    'median_Interval_of_arrival_time_of_backward_traffic_ratio',
    'max_Interval_of_arrival_time_of_backward_traffic_ratio',
    'min_Interval_of_arrival_time_of_backward_traffic_ratio',
    'std_Interval_of_arrival_time_of_backward_traffic_ratio',
    'var_Interval_of_arrival_time_of_backward_traffic_ratio',
    'total_ttl_forward_traffic_ratio',
    'std_ttl_forward_traffic_ratio',
    'mean_ttl_forward_traffic_ratio',
    'max_ttl_forward_traffic_ratio',
    'min_ttl_forward_traffic_ratio',
    'var_ttl_forward_traffic_ratio',
    'median_ttl_forward_traffic_ratio',
]

ALL_TIME_COLS = PKT_TIME_COLS + SESS_TIME_COLS

PAYLOAD_CANDIDATES = [
    'mean_Length_of_IP_packets',    'median_Length_of_IP_packets',
    'max_Length_of_IP_packets',     'min_Length_of_IP_packets',
    'std_Length_of_IP_packets',     'var_Length_of_IP_packets',
    'mean_Length_of_TCP_payload',   'median_Length_of_TCP_payload',
    'max_Length_of_TCP_payload',    'min_Length_of_TCP_payload',
    'std_Length_of_TCP_payload',    'var_Length_of_TCP_payload',
    'mean_Length_of_TCP_packet_header',  'median_Length_of_TCP_packet_header',
    'max_Length_of_TCP_packet_header',   'min_Length_of_TCP_packet_header',
    'std_Length_of_TCP_packet_header',   'var_Length_of_TCP_packet_header',
    'mean_Length_of_IP_packet_header',   'median_Length_of_IP_packet_header',
    'max_Length_of_IP_packet_header',    'min_Length_of_IP_packet_header',
    'std_Length_of_IP_packet_header',    'var_Length_of_IP_packet_header',
    'mean_TCP_windows_size_value',  'median_TCP_windows_size_value',
    'max_TCP_windows_size_value',   'min_TCP_windows_size_value',
    'std_TCP_windows_size_value',   'var_TCP_windows_size_value',
    'mean_Length_of_TCP_segment(packet)', 'median_Length_of_TCP_segment(packet)',
    'max_Length_of_TCP_segment(packet)',  'min_Length_of_TCP_segment(packet)',
    'std_Length_of_TCP_segment(packet)',  'var_Length_of_TCP_segment(packet)',
    'std_forward_packet_length',    'mean_forward_packet_length',
    'max_forward_packet_length',    'min_forward_packet_length',
    'var_forward_packet_length',    'median_forward_packet_length',
    'std_backward_packet_length',   'mean_backward_packet_length',
    'max_backward_packet_length',   'min_backward_packet_length',
    'var_backward_packet_length',   'median_backward_packet_length',
]

ENC_TIME_SESS_COLS = [
    'flow_duration_enc',
    'flow_duration_of_forward_traffic_enc',
    'flow_duration_of_backward_traffic_enc',
    'mean_Interval_of_arrival_time_of_forward_traffic_enc',
    'median_Interval_of_arrival_time_of_forward_traffic_enc',
    'max_Interval_of_arrival_time_of_forward_traffic_enc',
    'min_Interval_of_arrival_time_of_forward_traffic_enc',
    'std_Interval_of_arrival_time_of_forward_traffic_enc',
    'var_Interval_of_arrival_time_of_forward_traffic_enc',
    'mean_Interval_of_arrival_time_of_backward_traffic_enc',
    'median_Interval_of_arrival_time_of_backward_traffic_enc',
    'max_Interval_of_arrival_time_of_backward_traffic_enc',
    'min_Interval_of_arrival_time_of_backward_traffic_enc',
    'std_Interval_of_arrival_time_of_backward_traffic_enc',
    'var_Interval_of_arrival_time_of_backward_traffic_enc',
    'total_ttl_forward_traffic_enc',
    'std_ttl_forward_traffic_enc',
    'mean_ttl_forward_traffic_enc',
    'max_ttl_forward_traffic_enc',
    'min_ttl_forward_traffic_enc',
    'var_ttl_forward_traffic_enc',
    'median_ttl_forward_traffic_enc',
    'total_ttl_backward_traffic_enc',
    'std_ttl_backward_traffic_enc',
    'mean_ttl_backward_traffic_enc',
    'max_ttl_backward_traffic_enc',
    'min_ttl_backward_traffic_enc',
    'var_ttl_backward_traffic_enc',
    'median_ttl_backward_traffic_enc',
    'Total_Time_to_live_enc',
    'Total_length_of_forward_payload_enc',
    'Total_length_of_backward_payload_enc',
]
